/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface AnalysisResult {
  variableDeclarations: number
  functionDeclarations: number
  classDeclarations: number
  exportDeclarations: number
}
export declare function analysisSourceCode(sourceCode: string): AnalysisResult
export declare function plus100(input: number): number
